backend:
  name: github
  repo: Blinkx-Original/tidb-cloud-starter   # <— tu repo
  branch: main
  base_url: /api/decap                        # <— nuestro proxy OAuth (lo creamos abajo)
  auth_endpoint: auth

media_folder: "public/uploads"   # dónde se guardan en el repo
public_folder: "/uploads"        # ruta pública en el sitio

publish_mode: editorial_workflow  # opcional (borradores + PRs)

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "slug", label: "Slug", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "excerpt", label: "Excerpt", widget: "text" }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: "category", label: "Category", widget: "string" }
      - { name: "cta_label", label: "CTA Label", widget: "string", required: false }
      - { name: "cta_url", label: "CTA URL", widget: "string", required: false }
      - { name: "body", label: "Content", widget: "markdown" }
